[package]
name = 'multi-app'
version = '0.1.0'
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = '*'
eframe = { path = '../../crates/eframe', default-features = false, features = ['default_fonts', 'wgpu'] }
